### ISSUE TITLE
Comment on you domaci ukol 1

### ISSUE THREAD

**Issue by KristynaSodomkova** [tnavratilova/Czechitas---Python#1]
Ahoj Terko, vse v poradku, pisu si, ze mas ukol splneny. Nemam bohuzel ani zadne vylepseni, kterre by me k tvemu kodu napadlo. Snad jen pokud bys chtela, muzes si posunout kod, kde resisnazev Residence, jestli je to komercni nebo ne. To by slo vytahnout do propertu te classy Residence, mohlo by se to mozna hodit, kdzbz si to chtel clovek overit nejak zvlast. Ale to je opravdu jen velmi slabe doporuceni. Jinak vse OK!

Co je ale spis technicka poznamka k zadani ukolu - mela jsi tusim vytvorit issue tady u tohoto ukolu, ale zadne tady nebylo, tak jsem ho udelala ja. Muzeme se na to podivat v breakoutroomu, abys to priste uz vedela. Neni to nic sloziteho, takze pohoda :)

**Comment by tnavratilova** [comment]
Děkuju moc. 

O tom Issue vím, ale bohužel mi tě nešlo označit dřív než jsi potvrdila pozvánku. Tak jsem měla v plánu to udělat poté, co to potvrdíš :)
